# for development environment where we need to rebundle and restart server within the container, we can use the dev stage
FROM node:16.3.0-alpine
WORKDIR /home/node/root

COPY . .
RUN npm install

RUN apk update \
 && apk add --no-cache jq \
 && rm -rf /var/cache/apk/*
 
# required as sass depends on native modules which end up being bound onto the container
# and the container uses alpine so it does not support those native modules required by sass
# to work around that, have to rebuild sass for alpine 
RUN (cd client;npm rebuild node-sass) 

# same story for the prisma client
RUN (cd server;npx prisma generate)

CMD ["npm", "run", "start:local"]
