# for development environment where we need to rebundle and restart server within the container, we can use the dev stage
FROM node:16.3.0-alpine
WORKDIR /home/node/app

COPY package.json ./

RUN npm i
COPY . .

CMD ["npm", "run", "build:dev"]
